const { test, after, beforeEach } = require('node:test');
const assert = require('node:assert');
const request = require('supertest');
const app = require('../src/app');
const db = require('../src/db');

after(async () => {
  await db.pool.end();
});

beforeEach(async () => {
  await db.query('DELETE FROM webhook_events');
  await db.query('DELETE FROM usage_events');
  await db.query('DELETE FROM subscriptions');
});

test('GET /api/v1/invoices/current - retrieves current active draft invoice with accurate subtotal and line items', async () => {
  const res = await request(app)
    .get('/api/v1/invoices/current')
    .expect(200);

  assert.strictEqual(res.body.invoice.currency, 'USD');
  assert.strictEqual(res.body.invoice.plan_name, 'Free');
  assert.strictEqual(res.body.invoice.status, 'paid');
  assert.strictEqual(Array.isArray(res.body.invoice.line_items), true);
  assert.strictEqual(res.body.invoice.line_items.length, 6);
});

test('GET /api/v1/invoices - retrieves list of monthly invoices for tenant', async () => {
  const res = await request(app)
    .get('/api/v1/invoices')
    .expect(200);

  assert.strictEqual(Array.isArray(res.body.invoices), true);
  assert.strictEqual(res.body.invoices.length >= 1, true);
});

test('GET /api/v1/invoices/current - reflects usage costs generated by POST /api/v1/generate', async () => {
  // Upgrade to Pro plan first to have higher token limits
  await request(app)
    .post('/api/v1/subscription/checkout')
    .send({ plan_name: 'Pro' })
    .expect(200);

  // Generate 1,000,000 input tokens ($3.00 = 300 cents) and 100,000 output tokens ($1.50 = 150 cents)
  await request(app)
    .post('/api/v1/generate')
    .set('Idempotency-Key', 'invoice-gen-test-key-001')
    .send({
      input_tokens: 1000000,
      cached_tokens: 0,
      output_tokens: 100000,
      reasoning_tokens: 0,
    })
    .expect(200);

  const res = await request(app)
    .get('/api/v1/invoices/current')
    .expect(200);

  // Subtotal = Pro plan base price ($29.00 = 2900 cents) + 300 cents input + 150 cents output = 3350 cents
  assert.strictEqual(res.body.invoice.plan_name, 'Pro');
  assert.strictEqual(res.body.invoice.subtotal_cents, 3350);
  assert.strictEqual(res.body.invoice.total_cents, 3350);
});

test('GET /api/v1/invoices/:id - returns HTTP 404 Not Found for non-existent invoice ID', async () => {
  const res = await request(app)
    .get('/api/v1/invoices/invalid_invoice_999999')
    .expect(404);

  assert.strictEqual(res.body.error, 'Not Found');
  assert.strictEqual(res.body.message.includes('not found'), true);
});
